services:
  apis:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - .:/build
    depends_on:
      - db
    command: /bin/sh /build/entrypoint.sh

  db:
    image: mariadb:10.9
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    ports:
      - 3306:3306
